apiVersion: v1
kind: PersistentVolume
metadata:
  name: "rbd1" 
spec:
  capacity:
    storage: "1Gi" 
  accessModes:
    - "ReadWriteOnce" 
  rbd: 
    monitors:
      - "192.168.10.11:6789" 
      - "192.168.10.12:6789" 
      - "192.168.10.13:6789" 
    pool: k8s
    image: k8s-vol1
    user: admin
    secretRef:
      name: "ceph-secret" 
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: "Recycle"


