apiVersion: v1
kind: ReplicationController
metadata:
  name: liveness-exec-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: liveness-exec
    spec:
      containers:
      - name: liveness
        image: resin/rpi-raspbian
        args:
         - /bin/sh
         - -c
         - echo ok > /tmp/health; sleep 10; rm -rf /tmp/health; sleep 600
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/health
          initialDelaySeconds: 15
          timeoutSeconds: 1
