apiVersion: v1
kind: PersistentVolume
metadata:
 name: neo4jpv
spec:
 capacity:
   storage: 1Gi
 accessModes:
 - ReadWriteMany
 persistentVolumeReclaimPolicy: Retain
 nfs:
  path: /opt/data/neo4j
  server: 192.168.10.16
