apiVersion: v1
kind: Service
metadata:
  name: neo4jsvc
  labels:
    app: svc
spec:
#   type: LoadBalancer
  type: NodePort  
  ports:
  - port: 80
    targetPort: 7474
    nodePort: 30074
    protocol: TCP
  selector:
    app: neo4j
