apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxrc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: troyfontaine/armhf-nginx
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginxvolumehtml 
 #         subPath: html
        - mountPath: "/etc/nginx/conf.d"
          name: nginxvolumeconf
#          subPath: conf      
        ports:
        - containerPort: 80
      volumes:
      - name: nginxvolumehtml   
        persistentVolumeClaim:
         claimName: nginxhtmlpvc
      - name: nginxvolumeconf
        persistentVolumeClaim:
         claimName: nginxconfpvc


