apiVersion: v1
kind: PersistentVolume
metadata:
 name: nginxconfpv
spec:
 capacity:
   storage: 1Mi
 accessModes:
 - ReadOnlyMany
 persistentVolumeReclaimPolicy: Retain
 nfs:
  path: /opt/data/nginx/conf
  server: 192.168.10.16
