apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: mazzolino/armhf-nginx 
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginxvolume
        ports:
        - containerPort: 80
      volumes:
      - name: nginxvolume
        persistentVolumeClaim:
         claimName: nginxpv
