apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxrc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginxliveness
    spec:
      containers:
      - name: nginxliveness
        image: troyfontaine/armhf-nginx
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginxvolumehtml 
 #         subPath: html
        - mountPath: "/etc/nginx/conf.d"
          name: nginxvolumeconf
#          subPath: conf      
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz.html
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
      volumes:
      - name: nginxvolumehtml   
        persistentVolumeClaim:
         claimName: nginxhtmlpvc
      - name: nginxvolumeconf
        persistentVolumeClaim:
         claimName: nginxconfpvc


