apiVersion: v1
kind: PersistentVolume
metadata:
 name: nginxhtmlpv
spec:
 capacity:
   storage: 10Mi
 accessModes:
 - ReadOnlyMany
 persistentVolumeReclaimPolicy: Retain
 nfs:
  path: /opt/data/nginx/html
  server: 192.168.1.16

