apiVersion: v1
kind: Service
metadata:
  name: owncloudsvc
  labels:
    app: svc
spec:
#   type: LoadBalancer
  type: NodePort  
  sessionAffinity: ClientIP
  selector:
    app: owncloud
  externalIPs:
  - 192.168.1.16
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30180
    protocol: TCP
