apiVersion: v1
kind: PersistentVolume
metadata:
 name: owncloudpv
spec:
 capacity:
   storage: 1Gi
 accessModes:
 - ReadWriteMany
 persistentVolumeReclaimPolicy: Retain
 nfs:
  path: /opt/data/owncloud
  server: 192.168.1.16
