apiVersion: v1
kind: ReplicationController
metadata:
  name: owncloudrc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: owncloud
    spec:
      containers:
      - name: owncloud
        image: armv7/armhf-owncloud
        volumeMounts:
        - mountPath: "/var/www/html"
          name: owncloudvolume
        ports:
        - containerPort: 80
      volumes:
      - name: owncloudvolume
        persistentVolumeClaim:
         claimName: owncloudpv

