apiVersion: v1
kind: Service
metadata:
  name: piwebsrvsvc
  labels:
    app: piwebsrv
spec:
#   type: LoadBalancer
  type: NodePort  
  ports:
  - port: 7777
    targetPort: 7777
    nodePort: 30007
    protocol: TCP
  selector:
    app: piwebsrv
