apiVersion: v1
kind: PersistentVolume
metadata:
 name: piwebsrvpv
spec:
 capacity:
   storage: 512Mi
 accessModes:
 - ReadOnlyMany
 persistentVolumeReclaimPolicy: Retain
 nfs:
  path: /opt/data/rpi-websrv-data
  server: 192.168.10.16
