apiVersion: v1
kind: ReplicationController
metadata:
  name: piwebsrvrc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: piwebsrv
    spec:
      containers:
      - name: piwebsrv
        image: mahnkong/rpi-websrv:0.1.1
        volumeMounts:
        - mountPath: /rpi-websrv-data
          name: piwebsrvdata
        ports:
        - containerPort: 7777
      volumes:
      - name: piwebsrvdata
        persistentVolumeClaim:
         claimName: piwebsrvpvc
